-- Generated by Oracle SQL Developer Data Modeler 21.2.0.165.1515
--   at:        2022-05-26 14:11:23 CEST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE OR REPLACE VIEW Srednie_oceny_osob ( id_osoby, email, nazwisko, imie, srednia_ocena ) AS
SELECT
    os.id_osoby,
    os.email,
    os.nazwisko,
    os.imie,
    AVG(o.ocena) AS srednia_ocena
FROM
         odpowiedzi o
    INNER JOIN ankiety a ON ( o.id_ankiety = a.id_ankiety )
    INNER JOIN osoby   os ON ( a.id_agenta = os.id_osoby )
GROUP BY
    os.id_osoby,
    os.email,
    os.nazwisko,
    os.imie 
;

ALTER VIEW srednie_oceny_osob ADD CONSTRAINT sred_osb_pk PRIMARY KEY ( id_osoby ) DISABLE;

CREATE OR REPLACE VIEW Srednie_oceny_pytan ( kod_typu_ankiety, nr_pytania, tresc, srednia_ocena ) AS
SELECT
    p.kod_typu_ankiety,
    p.nr_pytania,
    p.tresc,
    AVG(o.ocena) AS srednia_ocena
FROM
         odpowiedzi o
    INNER JOIN pytania p ON o.kod_typu_ankiety = p.kod_typu_ankiety
                            AND o.nr_pytania = p.nr_pytania
GROUP BY
    p.kod_typu_ankiety,
    p.nr_pytania,
    p.tresc 
;

ALTER VIEW srednie_oceny_pytan ADD CONSTRAINT sred_pyt_pk PRIMARY KEY ( kod_typu_ankiety,
                                                                        nr_pytania ) DISABLE;

ALTER VIEW srednie_oceny_pytan ADD CONSTRAINT sred_pyt_tank_fk FOREIGN KEY ( kod_typu_ankiety )
    REFERENCES typy_ankiet ( kod_typu_ankiety )
DISABLE;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             0
-- CREATE INDEX                             0
-- ALTER TABLE                              0
-- CREATE VIEW                              2
-- ALTER VIEW                               3
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
